GET http://localhost:3000/tasks


###


POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name":"necesito un sitio web ",
    "descrption": "utilizando react-native"
}
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name":"necesito mejorar a avanzado en typescript",
    "descrption": "utilizando react-native"
}
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name":"necesito mejorar a avanzado en react",
    "descrption": "utilizando react-native"
}